[project]
name = "arclet-alconna-graia"
version = "0.9.0"
description = "Support Alconna to GraiaProject"
authors = [
    {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
dependencies = [
    "arclet-alconna<1.4.0, >=1.3.2",
    "arclet-alconna-tools>=0.2.0",
    "nepattern>=0.3.0",
    "creart-graia>=0.1.5",
    "creart>=0.2.1",
    "graia-amnesia>=0.5.0",
    "graia-ariadne<0.10.0, >=0.7.14",
    "graia-broadcast>=0.18.2",
    "graia-saya>=0.0.17",
    "graiax-shortcut>=0.2.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "AGPL-3.0"}
keywords = ["alconna", "graia", "dispatcher", "arclet"]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
[project.urls]
Homepage = "https://github.com/ArcletProject/Alconna-Graia"
Documentation = "https://arcletproject.github.io/docs/alconna/tutorial"
"Bug Reports" = "https://github.com/ArcletProject/Alconna/issues"
Source = "https://github.com/ArcletProject/Alconna"
[project.entry-points."creart.creators"]
alconna_behavior = "arclet.alconna.graia.create:AlconnaBehaviorCreator"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]

[tool.pdm.build]
includes = ["src/arclet"]
