[project]
name = "arclet-alconna-graia"
version = "0.0.15"
description = "Support Alconna to GraiaProject"
authors = [
    {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"},
]
dependencies = [
    "arclet-alconna<1.5.0, >=1.4.2",
    "arclet-alconna-tools>=0.3.0",
    "nepattern>=0.3.2",
    "arclet-alconna>=0.9.2",
    "graia-ariadne<0.7, >=0.6.16",
    "graia-saya>=0.0.16",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "AGPL-3.0"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[project.urls]
Homepage = "https://github.com/ArcletProject/Alconna-Graia"
Documentation = "https://arcletproject.github.io/docs/alconna/tutorial"
"Bug Reports" = "https://github.com/ArcletProject/Alconna/issues"
Source = "https://github.com/ArcletProject/Alconna"
[project.entry-points."creart.creators"]
alconna_behavior = "arclet.alconna.graia.create:AlconnaBehaviorCreator"

[tool]
[tool.pdm]

[tool.pdm.build]
includes = ["src/arclet"]
