includes = ["src/arclet/alconna/ariadne"]
raw-dependencies = [
    "arclet-alconna-graia<0.18.0, >= 0.18.0",
    "graia-ariadne<1.0.0, >=0.11.0",
]

[project]
name = "arclet-alconna-ariadne"
version = "0.18.0"
authors = [
    {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
dependencies = [

]
description = "Support Alconna to GraiaProject/Ariadne"
readme = "README.md"
license = {text = "AGPL-3.0"}
requires-python = ">=3.8"
keywords = ["alconna", "graia", "arclet"]

classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
[project.urls]
homepage = "https://github.com/ArcletProject/Alconna-Graia"
repository = "https://github.com/ArcletProject/Alconna-Graia"
