includes = ["src/arclet/alconna/avilla"]
raw-dependencies = [
    "arclet-alconna-graia<0.19.0, >= 0.18.3",
]

[project]
name = "arclet-alconna-avilla"
version = "0.18.3"
authors = [
    {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
dependencies = [
    "avilla-core>=1.0.0a24",
]
description = "Support Alconna to GraiaProject/Avilla"
readme = "README.md"
license = {text = "AGPL-3.0"}
requires-python = ">=3.8"
keywords = ["alconna", "graia", "arclet", "avilla"]

classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
[project.urls]
homepage = "https://github.com/ArcletProject/Alconna-Graia"
repository = "https://github.com/ArcletProject/Alconna-Graia"