includes = ["src/arclet/alconna/graia"]

[project]
name = "arclet-alconna-graia"
version = "0.18.1"
description = "Support Alconna to GraiaProject"
authors = [
    {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
readme = "README.md"
license = {text = "AGPL-3.0"}
requires-python = ">=3.8"
keywords = ["alconna", "graia", "arclet", "ariadne"]
dependencies = [
    "arclet-alconna<2.0.0, >=1.8.1",
    "arclet-alconna-tools<0.8.0, >=0.7.0",
    "tarina>=0.4.2",
    "nepattern<0.7.0, >=0.6.0",
    "creart>=0.3.0",
    "graia-amnesia>=0.5.0",
    "graia-broadcast>=0.18.2",
    "graia-saya>=0.0.17",
    "launart>=0.5.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
[project.urls]
homepage = "https://github.com/ArcletProject/Alconna-Graia"
repository = "https://github.com/ArcletProject/Alconna-Graia"
Documentation = "https://arcletproject.github.io/docs/alconna/tutorial"
"Bug Reports" = "https://github.com/ArcletProject/Alconna/issues"
Source = "https://github.com/ArcletProject/Alconna"


[project.entry-points."creart.creators"]
alconna_behavior = "arclet.alconna.graia.create:AlconnaBehaviorCreator"
